SELECT * FROM FUNCIONARIO

SELECT COUNT(CDCARGO), CDCARGO 
	FROM FUNCIONARIO
		GROUP BY CDCARGO

SELECT COUNT(*) FROM FUNCIONARIO

SELECT * FROM CARGO

SELECT COUNT(*) FROM CARGO

SELECT AVG(C.VRSALARIO) FROM CARGO C

SELECT MAX(C.VRSALARIO) FROM CARGO C

SELECT MIN(C.VRSALARIO) FROM CARGO C

SELECT SUM(C.VRSALARIO) FROM CARGO C


FUNCOES DE AGREGAÇÕES - USAR GROUP BY
COUNT = CONTAGEM
AVG = MÉDIA
SUM = SOMA
MIN = MÍNIMO
MAX = MÁXIMO