
/* CRIAR AS TABELAS */
CREATE TABLE CARGO (
    CDCARGO VARCHAR(3) identity primary key,
    NMCARGO VARCHAR(30) NOT NULL,
    VRSALARIO NUMERIC(18,2)
);

CREATE TABLE DEPTO (
    CDDEPTO VARCHAR(3) NOT NULL,
    NMDEPTO VARCHAR(30) NOT NULL,
    RAMAL CHAR(3)
);

CREATE TABLE FUNCIONARIO (
    NRMATRIC SMALLINT NOT NULL,
    NMFUNC VARCHAR(40) NOT NULL,
    DTADM DATE,
    SEXO CHAR(1),
    CDCARGO VARCHAR(3),
    CDDEPTO VARCHAR(3)
);

/* PRIMARY KEYS  - CHAVES PRIMARIAS */
ALTER TABLE CARGO 
ADD CONSTRAINT PK_CARGO 
PRIMARY KEY(CDCARGO);

ALTER TABLE DEPTO 
ADD CONSTRAINT PK_DEPTO 
PRIMARY KEY(CDDEPTO);


ALTER TABLE FUNCIONARIO 
ADD CONSTRAINT PK_NRMATRIC 
PRIMARY KEY (NRMATRIC);

/* FOREIGN KEYS - CHAVES ESTRANGEIRAS */
ALTER TABLE FUNCIONARIO 
ADD CONSTRAINT FK_CARGO 
FOREIGN KEY (CDCARGO)
REFERENCES CARGO (CDCARGO);

ALTER TABLE FUNCIONARIO 
ADD CONSTRAINT FK_DEPTO 
FOREIGN KEY (CDDEPTO)
REFERENCES DEPTO (CDDEPTO);


-- SQL/DML - DATA MANIPULATION LANGUAGE
--INSERT INSERIR REGISTROS
--UPDATE ATUALIZAR REGISTROS
--DELETE EXCLUIR REGISTROS
--SELECT CONSULTAR REGISTROS

SELECT * FROM CARGO

/* INSERE OS DADOS CARGO */
INSERT INTO CARGO (CDCARGO, NMCARGO, VRSALARIO) 
VALUES ('C1','COZINHEIRA',350);

INSERT INTO CARGO 
VALUES ('C3','AUX.ESCRITORIO',450);

INSERT INTO CARGO (NMCARGO, CDCARGO,  VRSALARIO) 
VALUES 
('C7','VIGIA',400),
('C2','MECANICO',750),
('C5','GERENTE',2300)



INSERT INTO CARGO (CDCARGO, NMCARGO) 
VALUES ('C4',600);

UPDATE CARGO 
	SET NMCARGO='ESCRITURARIO', VRSALARIO=600
		WHERE CDCARGO='C4' 

DELETE FROM CARGO WHERE VRSALARIO>300
/* INSERE OS DADOS DE DEPARTAMENTO */
INSERT INTO DEPTO VALUES ('D1','ADMINISTRACAO','221');
INSERT INTO DEPTO VALUES ('D2','OFICINA','235');
INSERT INTO DEPTO VALUES ('D3','SERVICOS GERAIS','243');
INSERT INTO DEPTO VALUES ('D4','VENDAS','258');


set dateformat dmy --MODIFICA PADRAO DATA PARA DIA/MES/ANO

/* INSERE OS DADOS DE FUNCIONARIO - SET DATEFORMAT DMY */
INSERT INTO FUNCIONARIO 
VALUES (1001,'JOAO SAMPAIO','10/08/1993','M','C2','D2'); 
INSERT INTO FUNCIONARIO VALUES (1004,'LUCIO TORRES','02/03/1994','M','C2','D2');
INSERT INTO FUNCIONARIO VALUES (1034,'ROBERTO PEREIRA','23/05/1992','M','C3','D1');
INSERT INTO FUNCIONARIO VALUES (1021,'JOSE NOGUEIRA','10/11/1994','M','C3','D1');
INSERT INTO FUNCIONARIO VALUES (1029,'RUTH DE SOUZA','05/01/1992','F','C1','D3');
INSERT INTO FUNCIONARIO VALUES (1095,'MARIA DA SILVA','03/09/1992','F','C4','D1');
INSERT INTO FUNCIONARIO VALUES (1023,'LUIZ DE ALMEIDA','12/01/1993','M','C2','D2');
INSERT INTO FUNCIONARIO VALUES (1042,'PEDRO PINHEIRO','29/07/1994','M','C4','D1');
INSERT INTO FUNCIONARIO VALUES (1048,'ANA SILVEIRA','01/06/1993','F','C5','D1');
INSERT INTO FUNCIONARIO VALUES (1015,'PAULO RODRIGUES','17/08/1992','M','C2','D2');

SELECT * FROM FUNCIONARIO

--3) Listar os cargos
SELECT * FROM CARGO;
SELECT C.* FROM CARGO C

--4)	Listar somente os funcion�rios; 
SELECT * FROM FUNCIONARIO;

--5)	Listar o nome dos funcion�rios do Cargo: C2;
SELECT F.NMFUNC FROM FUNCIONARIO F WHERE F.CDCARGO='C2';

--6)	Listar todos os funcion�rios do Depto=1 com sexo='f';
--AND (TODAS VERFICACOES TEM Q SER VERDADEIRAS PARA APRESENTAR O REGISTO)
--OR (UMA DAS VERFICACOES TEM Q SER VERDADEIRA PARA APRESENTAR O REGISTO)
--NOT (VALOR INVERSO OU DIFERENTE PARA APRESENTAR O REGISTRO

SELECT F.*
    FROM FUNCIONARIO F
      	  WHERE F.CDDEPTO='D1'AND
        	  SEXO = 'F' 

--7)	Listar o nome e DtAdm dos funcionarios 
--com Vrsalario inferior ah 600
 

SELECT F.NMFUNC, F.DTADM, C.VRSALARIO
	FROM FUNCIONARIO F, CARGO C
			WHERE F.CDCARGO = C.CDCARGO 
			AND C.VRSALARIO>600

-- 8)	Listar o nome dos funcion�rios, 
--nome de cargos e nome departamentos;

SELECT F.NMFUNC, C.NMCARGO, D.NMDEPTO
	FROM FUNCIONARIO F, CARGO C, DEPTO D						
		WHERE F.CDCARGO = C.CDCARGO
			AND F.CDDEPTO = D.CDDEPTO

--9)	Listar Nome dos funcion�rios e ramal para contato;
SELECT F.NMFUNC, D.RAMAL
	FROM FUNCIONARIO F, DEPTO D
		WHERE F.CDDEPTO = D.CDDEPTO



SELECT COUNT(*)
	FROM
		(SELECT F.NMFUNC,D.RAMAL,C.NMCARGO
		FROM FUNCIONARIO F, DEPTO D,CARGO C
		WHERE F.CDCARGO = C.CDCARGO 
		AND F.CDDEPTO = D.CDDEPTO) X

SELECT F.NMFUNC,D.RAMAL
		FROM FUNCIONARIO F, DEPTO D
			WHERE F.CDDEPTO = D.CDDEPTO

--10)	Listar Nome e DtAdm dos funcion�rios 
--contratados em 93 do sexo M;

SELECT F.NMFUNC, F.DTADM
	FROM FUNCIONARIO F
		WHERE YEAR(F.DTADM)=1993
			AND F.SEXO='M'





SELECT F.NMFUNC,F.DTADM
     FROM FUNCIONARIO F
      		WHERE YEAR (F.DTADM) = 1993 
			AND F.SEXO='M'

--11)	Listar NrMatric, NmFunc dos funcion�rios 
--contratos no m�s 08;

SELECT F.NRMATRIC, F.NMFUNC
	FROM FUNCIONARIO F
		WHERE MONTH(F.DTADM)=8
		


      SELECT F.NRMATRIC, F.NMFUNC
			FROM FUNCIONARIO F
				WHERE MONTH (F.DTADM)=8

--12)	Listar o nome de cada funcion�rio, 
--com o nome do departamento e o sal�rio de cada um.

SELECT
		F.NMFUNC, D.NMDEPTO, C.VRSALARIO
	FROM FUNCIONARIO F,DEPTO D, CARGO C
		WHERE F.CDCARGO = C.CDCARGO
		AND F.CDDEPTO = D.CDDEPTO


SELECT F.NMFUNC, C.NMCARGO, D.NMDEPTO, C.VRSALARIO
    FROM FUNCIONARIO F , CARGO C, DEPTO D
		 WHERE  F.CDCARGO=C.CDCARGO
		 AND F.CDDEPTO=D.CDDEPTO

--13)	Atualizar o nome do funcion�rio 
-- ANA SILVEIRA para PAULA SILVEIRA

UPDATE FUNCIONARIO 
	SET NMFUNC ='PAULA SILVEIRA' 
		WHERE NMFUNC='ANA SILVEIRA'

-- 14)	Atualizar o sal�rio de quem ganha menos de
--- 600 reais para 601,50

UPDATE CARGO 
	SET VRSALARIO = 601.5
		 WHERE VRSALARIO<600

-- 15)	Excluir o cargo C7

DELETE FROM CARGO 
WHERE CDCARGO = 'C7'

